### PR TITLE
add dynamic icons to relative brightness action

### PR DESCRIPTION
**Pull request by dkern**
As suggested before, I've added individual action icons for the relative brightness function. The icon changed according to the selected relative value.

image

# NOTE !
Please merge https://github.com/elgatosf/streamdeck-philipshue/pull/22 first! My fault. 😉

### CODE REVIEW

**Comment by dkern** [comment]
@tiptronic Is there a reason this is left open? :)

**Comment by tiptronic** [comment]
@dkern yes - the reason was: 'I forgot to merge' ;)

**Comment by dkern** [comment]
I was hoping this was the only issue. 😉 Thanks!

**Comment by tiptronic** [comment]
You're welcome & sorry for that

**Pull request merged**
