### PR TITLE
Add new Action: Color Cycle

### PR DESCRIPTION
**Pull request by dkern**
# What is added
A new Action has been added, to cycle between up to ten colors with one button. This can even be used as toggle, if only two colors have been configured. The action is an extension of the `Colors` action and is rewritten to support multiple colors in a row.

# Screenshots
sc1
sc2
sc3

# What else have been done
I made a little change to the `log()` function in `source/plugin/utils.js`, allowing it to log objects and elements correctly to the browser console. This little change don't break anything and will have nearly the same output as before on normal variables. As this was very useful for me on debugging I've added that too.

# What else HAS to be done
- Version has to be bumped.

- Create a new Release-Package. I haven't done this, because i thought you would like to make this by yourself.

- The Screenshot of the Repository should be updated too, to show the new function. ;)

- The following localizations are missing for the word `Colors` and the Action description:  
`es`, `fr`, `js`, `ko`, `zh_CN`  
```
{
  // ...
  "com.elgato.philips-hue.cycle": {
    "Name": "Cycle",
    "Tooltip": "Cycle between colors of your light."
  },
  // ...
  "Localization": {
    "PI": {
      // ...
      "Colors": "Colors",
      // ...
    },
    // ...
  }
}
```

### CODE REVIEW

**Comment by dkern** [comment]
Nobody around here?! 😞

**Comment by dkern** [comment]
Nobody around here anymore?!

@elgatosystems @Timac

**Comment by elgatosystems** [comment]
@dkern Thanks a lot for the PR! It took us some time to review your changes, sorry about that.
The new feature is great and we merged it.

We will bump the version and release an update to the plugin in the coming days to all users. We will add later the missing localizations.

Thanks again for the awesome work!

**Comment by elgatosystems** [comment]
The Philips Hue 1.2 plugin  is now live in the Stream Deck store for all users. The release is also available here: https://github.com/elgatosf/streamdeck-philipshue/releases/tag/1.2

Once we have the localizations, we will make an update. Thanks again for the great work!

**Pull request merged**
